org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 --enable-native-access=ALL-UNNAMED
# Relaxed for DSH client CI: do not fail the build on every Gradle warning.
org.gradle.warning.mode=summary
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableR8.fullMode=true
android.uniquePackageNames=false
android.dependency.useConstraints=false
android.r8.strictFullModeForKeepRules=false
android.newDsl=true
